### ISSUE TITLE
Barebones documentation

### ISSUE THREAD

**Issue by WWDrakey** [nomovok-opensource/cutedriver-driver#5]
For the component:
- Create initial non-transitory README.md
- Decide whether we want one wiki for the whole cuTeDriver, and depending on that, either: 1) Create minimal wiki page for one component with barebones documentation and linking wiki-pages for the other components OR 2) Minimal Wiki-pages for each component, with barebones documentation

**Comment by WWDrakey** [comment]
Decided that we'll go with one Wiki, which will be under agent_qt. Created a wiki page here linking to that.

**Comment by WWDrakey** [comment]
And... re-opening since the README is still uncreated.

**Comment by Paimen** [comment]
readme updated
