### ISSUE TITLE
Test runner CI friendly

### ISSUE THREAD

**Issue by rferrazz** [nomovok-opensource/cutedriver-driver#6]
I'm using cutedriver to run tests on an embedded device running a Qt based GUI.
In order to automate the testing process using a CI system I have created a docker image with the driver and sut_qt that is able to run tests on a remote device without having to install anything on the local machine.

Here you can find the image and the documentation on how to run it: https://hub.docker.com/r/rferrazz/cutedriver

It can be a faster and less painful way to run tests with the cutedriver framework
I wonder if you can mention it in your wiki in order to make people aware of its existence

**Comment by Paimen** [comment]
Sure we can add this to our wiki. Can we just copy your readme with links to your repository for starting point?

**Comment by rferrazz** [comment]
It will be great, thanks.

**Comment by Paimen** [comment]
Added section to wiki. Thank you for supporting this project.
